# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 398fc2a54d5ec3c781a9884580a94d42ddbf542a49042bd78fab1925fdd8c080bce0c61ae7ae23b2ab81e413cffef918827fd8ec55dc1aa4d183cc8ffaa9ec0c

test:
  secret_key_base: 47e898f91791dc095f29486c39cf69ce2ce2548a60bd59af05cede259cc5802b4a294a885b4aad92242e30bd532866979e4e672983635a2b02153e7ba597c9c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
